### ISSUE TITLE
Break homepage up into Templates

### ISSUE THREAD

**Issue by AskYous** [AskYous/Xerorex#2]
The current homepage has plenty of sections. For best practice purposes, these sections should be contained in another file template as shown in Angular's [templating tutorial](https://docs.angularjs.org/tutorial/step_06) (these are known as **partials**). The sections currently on the homepage include the following:
1. A Navbar.
2. A Carousel.
3. A Marketing Section.
4. A Featurette Section.
5. A Footer.

These should be converted into partials. The template file would put the above sections to their own `.html` file. However, since the navbar and the footer would be displayed on almost every page, they do not need their own template file. So the new files would include:
1. Carousel.html
2. Marketing.html
3. Featurette.html

And these would be placed into a folder located in `partials/homepage/`. This can be implemented using the link to Angular's templating tutorial linked above.

**Comment by msk1990** [comment]
This task should be divided into subtasks

**Comment by AskYous** [comment]
Ya, I'll convert it into a milestone and separate these into tasks.
